server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Se o utilizador fizer F5 numa página (ex: /app/clientes), o Nginx não dá erro 404
    location / {
        try_files $uri $uri/ /index.html;
    }

    # A MAGIA DO PROXY: Lembras-te de termos posto apiUrl: '/api' no Angular?
    # O Nginx apanha os pedidos e reencaminha-os para o contentor do Java!
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}