# 1. Redirecionar os desatentos (HTTP para HTTPS)
server {
    listen 80;
    server_name gestorflow.178.104.156.13.nip.io;
    return 301 https://$host$request_uri;
}

# 2. O Cofre Forte (HTTPS)
server {
    listen 443 ssl;
    server_name gestorflow.178.104.156.13.nip.io;

    ssl_certificate /etc/letsencrypt/live/gestorflow.178.104.156.13.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gestorflow.178.104.156.13.nip.io/privkey.pem;

    # O teu frontend Angular
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # O teu Backend Java
    location /api/ {
        # A BARRA FATAL FOI APAGADA AQUI:
        proxy_pass http://backend:8080; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 1. Acesso ao Grafana (ex: logs.gestorflow.178.104.156.13.nip.io)
    location /grafana/ {
        proxy_pass http://gestorflow-grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Túnel Seguro para o Loki (Para o teu Mac enviar logs)
    location /loki/api/v1/push {
        # Proteção com utilizador e password (terás de gerar um ficheiro .htpasswd)
        auth_basic "Restrito a Engenharia";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://gestorflow-loki:3100/loki/api/v1/push;
        proxy_set_header Host $host;
    }
}