version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gestorflow-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gestorflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./GestorFlowJava
    container_name: gestorflow-backend
    # APAGÁMOS AS PORTS DAQUI POR SEGURANÇA!
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gestorflow
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - jwt.secret=${JWT_SECRET}
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./gestor-flow-web
    container_name: gestorflow-frontend
    ports:
      - "80:80" 
      - "443:443"  # <-- PORTA DO CADEADO
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # <-- LIGAÇÃO AO CERTIFICADO DO SERVIDOR
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: