# --- Configuração do Servidor ---
server.port=8080

# --- Configuração da Base de Dados (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/gestorflow
spring.datasource.username=gestor
spring.datasource.password=gestorflow123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuração do JPA / Hibernate ---
# update: Se mudares o código Java, ele atualiza a tabela na BD automaticamente
spring.jpa.hibernate.ddl-auto=create

# Mostra o SQL na consola (útil para veres o que o backend está a fazer)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto correto para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect