# --- Configuração do Servidor ---
server.port=8080

# --- Configuração da Base de Dados (NEON CLOUD) ---
# Aqui está o link modificado com o jdbc:postgresql://
spring.datasource.url=jdbc:postgresql://ep-little-recipe-agi5j5vs-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dVMNR5mG6OuQ
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuração do JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect